"""The symbols netskope-cli imports must keep resolving.

This is a deliberate coupling check between two repos that ship together, not a
backward-compatibility guarantee: it pins the paths the CLI uses *today*. When a
path moves, move the CLI and regenerate this table — do not add a re-export to
satisfy it.

Generated by an AST sweep of the CLI worktree.
"""

from __future__ import annotations

import importlib

import pytest

CLI_IMPORTS = [
    ("netskope", "NetskopeClient"),
    ("netskope", "exceptions"),
    ("netskope", "models"),
    ("netskope.core.pagination", "Page"),
    ("netskope.datasearch", "DATASEARCH_PAGE_CAP"),
    ("netskope.datasearch", "DatasearchWindow"),
    ("netskope.datasearch", "ScanStopReason"),
    ("netskope.datasearch", "ScanSummary"),
    ("netskope.exceptions", "NetskopeError"),
    ("netskope.exceptions", "ResponseValidationError"),
    ("netskope.models.administration", "AdminUser"),
    ("netskope.models.aicc", "AiccAlertMatrix"),
    ("netskope.models.aicc", "AiccAlertPolicies"),
    ("netskope.models.aicc", "AiccApplication"),
    ("netskope.models.aicc", "AiccBreakdown"),
    ("netskope.models.aicc", "AiccDataCoverage"),
    ("netskope.models.aicc", "AiccEntityCounts"),
    ("netskope.models.aicc", "AiccIdentity"),
    ("netskope.models.aicc", "AiccKpi"),
    ("netskope.models.aicc", "AiccMcpServer"),
    ("netskope.models.aicc", "AiccQuery"),
    ("netskope.models.aicc", "AiccSort"),
    ("netskope.models.aicc", "AiccUsage"),
    ("netskope.models.alerts", "Alert"),
    ("netskope.models.alerts", "DatasearchBucket"),
    ("netskope.models.atp", "AtpUrlScan"),
    ("netskope.models.cci", "CciAppQuery"),
    ("netskope.models.cci", "CciTagCreate"),
    ("netskope.models.cci", "CciTagName"),
    ("netskope.models.cci", "CciTagPatch"),
    ("netskope.models.common", "NetskopeModel"),
    ("netskope.models.dem", "AdemApplication"),
    ("netskope.models.dem", "DemQueryResult"),
    ("netskope.models.devices", "Device"),
    ("netskope.models.devices", "DeviceTag"),
    ("netskope.models.dns", "DnsDeployment"),
    ("netskope.models.dns", "DnsInheritanceGroupCreate"),
    ("netskope.models.dns", "DnsInheritanceGroupDeployment"),
    ("netskope.models.dns", "DnsInheritanceGroupPatch"),
    ("netskope.models.dns", "DnsProfileCreate"),
    ("netskope.models.dns", "DnsProfilePatch"),
    ("netskope.models.dspm", "DspmResourceType"),
    ("netskope.models.dspm", "SortOrder"),
    ("netskope.models.events", "Event"),
    ("netskope.models.incidents", "Anomaly"),
    ("netskope.models.incidents", "IncidentNote"),
    ("netskope.models.incidents", "IncidentUpdateResult"),
    ("netskope.models.infrastructure", "LocalBrokerCreate"),
    ("netskope.models.infrastructure", "LocalBrokerPatch"),
    ("netskope.models.infrastructure", "UpgradeProfileCreate"),
    ("netskope.models.infrastructure", "UpgradeProfileUpdate"),
    ("netskope.models.npa_policy", "NpaGroupOrder"),
    ("netskope.models.npa_policy", "NpaPolicyGroupCreate"),
    ("netskope.models.npa_policy", "NpaPolicyGroupPatch"),
    ("netskope.models.npa_policy", "NpaPolicyRuleCreate"),
    ("netskope.models.npa_policy", "NpaPolicyRulePatch"),
    ("netskope.models.nsiq", "RecategorizationRequest"),
    ("netskope.models.nsiq", "UrlLookup"),
    ("netskope.models.nsiq", "UrlRecategorization"),
    ("netskope.models.private_apps", "PrivateAppCreate"),
    ("netskope.models.private_apps", "PrivateAppDiscoveryRequest"),
    ("netskope.models.private_apps", "PrivateAppPatch"),
    ("netskope.models.private_apps", "PrivateAppProtocolSpec"),
    ("netskope.models.private_apps", "PrivateAppPublisherSpec"),
    ("netskope.models.publishers", "Publisher"),
    ("netskope.models.publishers", "PublisherAlertsConfigurationPatch"),
    ("netskope.models.rbac", "ApiGroupGrant"),
    ("netskope.models.rbac", "RbacRoleSummary"),
    ("netskope.models.rbac", "RoleCreate"),
    ("netskope.models.rbac", "RoleMutationReceipt"),
    ("netskope.models.rbac", "RolePatch"),
    ("netskope.models.rbi", "RbiTemplate"),
    ("netskope.models.scim", "ScimGroupCreate"),
    ("netskope.models.scim", "ScimGroupPatch"),
    ("netskope.models.scim", "ScimUserCreate"),
    ("netskope.models.scim", "ScimUserPatch"),
    ("netskope.models.steering", "IPSecTunnelCreate"),
    ("netskope.models.steering", "IPSecTunnelPatch"),
    ("netskope.models.steering", "SteeringSettings"),
    ("netskope.models.users", "UmGroup"),
    ("netskope.models.users", "UmUser"),
    ("netskope.models.users", "UserQuery"),
    ("netskope.resources.dspm.resource", "DspmResource"),
    ("netskope.resources.shared.aicc_endpoint", "AiccCollection"),
    ("netskope.resources.shared.aicc_endpoint", "AiccRead"),
    ("netskope.response", "ApiResponse"),
]


@pytest.mark.parametrize("module,symbol", CLI_IMPORTS)
def test_the_cli_can_still_import_it(module: str, symbol: str) -> None:
    assert hasattr(importlib.import_module(module), symbol), (
        f"netskope-cli imports {symbol} from {module}; it no longer resolves"
    )
